#!/bin/bash

# Define uma função para exibir mensagens
print_message() {
    echo -e "\033[1;31m[✔] $1 \033[0m"
}

# Navega para o diretório home do usuário
cd ~ || exit
print_message "Pasta ${PWD} - Aberta. Baixando repositório (vmware-host-modules) ..."

# Clona o repositório do GitHub
git clone https://github.com/mkubecek/vmware-host-modules.git

# Instala cabeçalhos do Linux
print_message "Instalando cabeçalhos do Linux - Corrigindo cabeçalhos Linux ausentes."
apt update && apt upgrade -y && apt autoremove -y
apt install linux-headers-"$(uname -r)" -y

# Altera as permissões do diretório clonado
chmod 777 -R vmware-host-modules

# Navega para o diretório do repositório clonado
cd vmware-host-modules || exit
print_message "Pasta ${PWD} - Aberta. Agora vamos compilar os componentes."

# Solicita a versão do VMware Workstation
print_message "Informe a versão do VMware Workstation. Ex.: 16.2.3"
read -r versao
git checkout workstation-"$versao"

# Compila e instala os módulos
print_message "Aguarde enquanto instalamos todos os componentes..."
make
sudo make install
sudo systemctl restart vmware.service

print_message "Tudo pronto!"
